# Generated by Django 4.2.1 on 2023-08-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageevents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_of_event', models.DateField()),
                ('time_of_event', models.TimeField()),
                ('description', models.TextField(max_length=255)),
                ('preview', models.ImageField(upload_to='preview/%Y/%m/%d/')),
                ('need_team', models.BooleanField()),
                ('quantity_of_participant', models.IntegerField()),
                ('all_free_place', models.IntegerField()),
                ('place_of_meeting', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageevents.listuniversity')),
            ],
        ),
    ]
