# Generated by Django 4.2.1 on 2023-08-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageevents', '0002_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date_of_event', '-time_of_event'], 'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='events',
            name='all_free_place',
            field=models.IntegerField(verbose_name='Свободные места'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='need_team',
            field=models.BooleanField(verbose_name='Необходимость команды'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageevents.listuniversity', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='events',
            name='place_of_meeting',
            field=models.CharField(max_length=100, verbose_name='Место встречи'),
        ),
        migrations.AlterField(
            model_name='events',
            name='preview',
            field=models.ImageField(upload_to='preview/%Y/%m/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='events',
            name='quantity_of_participant',
            field=models.IntegerField(verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_of_event',
            field=models.TimeField(verbose_name='Время мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
